### ISSUE TITLE
Errors when run "eventClassificationNiehorsterSiuLi2015.m"

### ISSUE THREAD

**Issue by JU-THU** [dcnieho/NystromHolmqvist2010#1]
Hi,

When I ran "eventClassificationNiehorsterSiuLi2015.m", it showed that 'Interleave' cannot be identified in plotClassification.m(Line 229). Is the function 'interleave' missing?

Thanks.

**Comment by dcnieho** [comment]
Yes, that turns out to be part of a toolbox i always have installed. Thanks for the report!
