### ISSUE TITLE
Just a question related to saccade and fixation detection.

### ISSUE THREAD

**Issue by AlfredLTennyson** [dcnieho/NystromHolmqvist2010#2]
In Nystrom,Holmqvist 2010 algorithm, all the steps are nicely given.
Since I am new to saccade detection stuff, i was wondering -
1) I have eye gaze data(monocular) in X and Y coordinates (in degrees of visual angle as it was imported from MONKEYLOGIC).
2) Should the blinks detection be done first? In the Nystrom,Holmqvist 2010 paper it is not entirely clear when should blink detection be done.
3) https://github.com/AlfredLTennyson/eye_gaze_data_for_1_trial/blob/main/T_Trial1.tsv
This is the data for one trial.
4) This is the eyeX vs eyeY plot.(10 trials)
![image](https://user-images.githubusercontent.com/114279791/195998101-ec86d6bf-00f0-4cb1-9705-3656c73200fc.png)
5) This is the velocity X vs time plot. The huge peak is supposed to be a saccade. (10 trials)
![image](https://user-images.githubusercontent.com/114279791/195998142-3b1fcef8-62f6-4123-a943-66dbe16bac9d.png)
6)this is the eyeX(position of eye in x coordinates in degrees)vs time (trial 1)
![image](https://user-images.githubusercontent.com/114279791/195998198-ee80bab8-53a6-4f37-9f92-3dfe0a01c310.png)

**Comment by AlfredLTennyson** [comment]
My question is, i just want to detect and plot saccades/fixations.
How should i approach it?
I will be glad if you can tell me what functions in your repository to use in sequence.
Thanks a ton!!

**Comment by dcnieho** [comment]
Hi Alfred,

Our code comes with demos, adapt those to read in your data.
But you seem to be using python? Then perhaps https://github.com/dcnieho/I2MC_Python is more suitable for you.

**Comment by AlfredLTennyson** [comment]
Hello,thanks a ton for replying.
One question , my data is already in degrees,will the algorithm work?

**Comment by AlfredLTennyson** [comment]
Also my data doesnt have pupil recording.

**Comment by dcnieho** [comment]
As it is, the code won't work when input is in degrees. You'll have to adapt the code. At minimum you'll have to remove the stage where pixels are converted to degrees, but i am not sure if that's sufficient or if pixels are used anywhere else in the code. The main parts of the algorithm however use position and velocity in degrees i think
