### ISSUE TITLE
getTs missing?

### ISSUE THREAD

**Issue by jtur044** [dcnieho/NystromHolmqvist2010#3]
Is getTs.m missing?

**Comment by dcnieho** [comment]
Can you send me the full error from the command line?

**Comment by jtur044** [comment]
Hello Diederick

Apols for lack of detail in my “report”.
Ita due to a check for lsim.m (and can be bypassed).

eventClassificationNiehorsterSiuLi2015


S1_R1
  N blink samples: 353 (0.74%)
Unrecognized function or variable 'getTs'.

Error in CanonicalDiscreteSSModel (line 4)
    Ts = getTs(sys);

Error in cutSaccades>cutSaccadesImplementation (line 154)
        X(sIdx:end) = CanonicalDiscreteSSModel(ETparams.sysdt,velX(sIdx:end)).' + X(sIdx);

Error in cutSaccades (line 53)
out = cutSaccadesImplementation(data.deg.Azi,...

Error in eventClassificationNiehorsterSiuLi2015 (line 100)
    data = cutSaccades(data,ETparams,cutPosTraceMode,cutVelTraceMode,extraCut,cutSaccadeSkipWindow);

J

**Comment by dcnieho** [comment]
Thanks for the interest in my code and the report! I indeed seem to have
forgotten to include that function. I am not near the computer that would
contain it a for a week, but will fix it as soon as i can!

**Comment by dcnieho** [comment]
I have resolved the issue. Please let me know if it works for you now :)
